language: node_js
branches:
  only:
    - master
node_js:
  - "12.14.1"
cache:
  directories:
    - node_modules # NPM packages
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libavahi-compat-libdnssd-dev -y
  - npm install -g npm@6.13.4
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run preflight && npm run build
